// Words that never make a useful research-theme label in a title bigram.
export const THEME_STOP_WORDS = new Set([
    // Function words
    'the', 'a', 'an', 'of', 'in', 'on', 'for', 'and', 'or', 'to', 'with',
    'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'has',
    'have', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
    'may', 'might', 'can', 'shall', 'not', 'no', 'but', 'if', 'at', 'as',
    'it', 'its', 'this', 'that', 'these', 'those', 'their', 'them', 'they',
    'we', 'our', 'how', 'what', 'which', 'who', 'whom', 'when', 'where',
    'why', 'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other',
    'some', 'such', 'than', 'too', 'very', 'also', 'just', 'about', 'above',
    'after', 'again', 'between', 'into', 'through', 'during', 'before',
    'via', 'under', 'over', 'upon', 'within', 'without', 'along', 'since',
    // Academic verbs/gerunds that aren't topics
    'using', 'based', 'exploring', 'examining', 'understanding', 'investigating',
    'analyzing', 'analysing', 'assessing', 'evaluating', 'measuring', 'testing',
    'comparing', 'developing', 'building', 'creating', 'designing', 'proposing',
    'presenting', 'showing', 'demonstrating', 'revealing', 'suggesting',
    'explaining', 'predicting', 'modeling', 'modelling', 'determining',
    'identifying', 'mapping', 'tracking', 'monitoring', 'implementing',
    'applying', 'adopting', 'integrating', 'combining', 'linking', 'bridging',
    'rethinking', 'reconsidering', 'revisiting', 'extending', 'expanding',
    'enhancing', 'improving', 'increasing', 'reducing', 'enabling', 'driving',
    'shaping', 'influencing', 'affecting', 'mediating', 'moderating',
    // Common academic nouns that are too generic
    'new', 'study', 'analysis', 'research', 'approach', 'role', 'effect',
    'effects', 'impact', 'case', 'evidence', 'towards', 'toward', 'among',
    'across', 'review', 'results', 'findings', 'implications', 'perspective',
    'perspectives', 'framework', 'model', 'models', 'theory', 'theories',
    'conceptual', 'empirical', 'systematic', 'comparative', 'critical',
    'introduction', 'editorial', 'commentary', 'response', 'reply', 'note',
    'chapter', 'paper', 'article', 'literature', 'future', 'directions',
    'special', 'issue', 'part', 'volume',
    // Common adjectives/adverbs that aren't topics
    'really', 'highly', 'fully', 'merely', 'largely', 'mainly', 'primarily',
    'particularly', 'especially', 'generally', 'currently', 'recently',
    'increasingly', 'different', 'various', 'several', 'multiple',
    'first', 'second', 'third', 'early', 'late', 'recent', 'current',
    'good', 'better', 'best', 'high', 'low', 'large', 'small', 'long', 'short',
    // Additional common title words that don't indicate topics
    'challenges', 'opportunities', 'strategies', 'practices', 'processes',
    'outcomes', 'determinants', 'antecedents', 'consequences', 'dynamics',
    'patterns', 'mechanisms', 'factors', 'dimensions', 'aspects',
    'definition', 'overview', 'agenda', 'assessment', 'exploration',
    'investigation', 'examination', 'discussion', 'considerations',
    'automated', 'automatic', 'semi-automated', 'manual',
    'local', 'national', 'international', 'regional',
    'potential', 'possible', 'proposed', 'alternative', 'traditional',
    'comprehensive', 'preliminary', 'initial', 'advanced', 'novel',
    'ethical', 'practical', 'theoretical', 'methodological',
    // Verbs and verb-like words that leak into bigrams
    'seeing', 'believing', 'making', 'taking', 'getting', 'going', 'looking',
    'working', 'thinking', 'knowing', 'finding', 'giving', 'telling', 'feeling',
    'becoming', 'keeping', 'leaving', 'putting', 'running', 'setting', 'turning',
    'bringing', 'holding', 'letting', 'beginning', 'seeming', 'helping', 'talking',
    'moving', 'living', 'playing', 'standing', 'losing', 'paying', 'meeting',
    'sitting', 'opening', 'growing', 'walking', 'winning', 'teaching', 'offering',
    'learning', 'considering', 'appearing', 'leading', 'rising', 'changing',
    'coming', 'reading', 'calling', 'following', 'adding', 'reaching', 'serving',
    'pulling', 'pushing', 'covering', 'cutting', 'crossing', 'breaking', 'passing',
    'raising', 'addressing', 'reporting', 'engaging', 'promoting', 'achieving',
    'supporting', 'providing', 'ensuring', 'delivering', 'stimulating', 'fostering',
    'leveraging', 'harnessing', 'unlocking', 'unleashing', 'overcoming',
    'navigating', 'transforming', 'disrupting', 'accelerating', 'redefining',
    'reimagining', 'uncovering', 'unraveling', 'unpacking', 'deconstructing',
    'drives', 'driven', 'matters',
    // Common adjective/noun fragments that aren't topics
    'curious', 'personal', 'reliability', 'gut', 'shop',
    'collected', 'papers', 'adventures', 'character', 'years',
    'vol', 'swiss', 'berlin',
    'real', 'world', 'open', 'key', 'big', 'end', 'old', 'age', 'set',
    'well', 'way', 'much', 'back', 'turn', 'look', 'take', 'make', 'give',
    'come', 'keep', 'let', 'say', 'get', 'got', 'put', 'run', 'see', 'seem',
    'need', 'try', 'ask', 'use', 'find', 'tell', 'call', 'play', 'work',
    'move', 'live', 'believe', 'bring', 'happen', 'write', 'provide', 'sit',
    'stand', 'lose', 'pay', 'meet', 'include', 'continue', 'learn', 'change',
    'lead', 'understand', 'watch', 'follow', 'stop', 'speak', 'read', 'add',
    'spend', 'grow', 'win', 'teach', 'show', 'hear', 'offer', 'remember',
    'consider', 'appear', 'love', 'buy', 'wait', 'die', 'send', 'expect',
    'build', 'stay', 'fall', 'reach', 'kill', 'remain', 'suggest', 'raise',
    'pass', 'sell', 'require', 'report', 'decide', 'pull',
    // Publication-type words
    'book', 'books', 'handbook', 'proceedings', 'conference', 'journal',
    'preprint', 'thesis', 'dissertation', 'monograph', 'manuscript',
    // Common non-English words that slip through (no diacritics)
    'der', 'die', 'das', 'und', 'ein', 'eine', 'einer', 'des', 'dem',
    'den', 'auf', 'aus', 'bei', 'mit', 'von', 'zum', 'zur', 'als',
    'les', 'des', 'une', 'dans', 'sur', 'par', 'pour', 'avec', 'aux',
    'het', 'een', 'van', 'voor', 'met', 'niet', 'dat', 'zij', 'ook',
    'wel', 'nog', 'maar', 'wat', 'hoe', 'wie', 'waar', 'naar', 'tot',
    'over', 'door', 'kan', 'moet', 'mag', 'zal', 'zou', 'hebben', 'zijn',
    'worden', 'deze', 'dit', 'die', 'ons', 'hun', 'uw', 'meer', 'veel',
    'alle', 'geen', 'elk', 'zo', 'dan', 'dus', 'want', 'omdat',
    'oude', 'dag', 'geld', 'financi', 'financieel', 'financiele',
    'veerkracht', 'pensioen', 'pensioenen', 'sparen', 'beleggen',
    'inkomen', 'schuld', 'schulden', 'huishouden', 'consument',
    'onderzoek', 'studie', 'rapport', 'bijdrage', 'effect', 'effecten',
    'zetten', 'mensen', 'geven', 'maken', 'nemen', 'doen', 'laten', 'zien',
    'werken', 'denken', 'weten', 'vinden', 'kopen', 'keuze', 'gedrag',
    'kinderen', 'jongeren', 'ouderen', 'vrouwen', 'mannen', 'klanten',
    'aan', 'actie', 'punt', 'recht', 'deel', 'plaats', 'tijd', 'jaar',
    'hulp', 'steun', 'weg', 'huis', 'land', 'stad', 'werk', 'leven',
    'zwischen', 'oder', 'aber', 'wenn', 'weil', 'nach', 'kann', 'wird',
    'sind', 'nicht', 'auch', 'noch', 'nur', 'sehr', 'schon', 'doch',
    'unter', 'gegen', 'durch', 'ohne', 'jede', 'alle', 'sein', 'meine',
    'ihre', 'seine', 'unser', 'wir', 'sie', 'sich',
    'theorie', 'antwort', 'briefe', 'sechzig', 'english', 'translation',
    'letter', 'jul', 'jan', 'feb', 'mar', 'apr', 'jun', 'aug', 'sep', 'oct', 'nov', 'dec',
]);
