import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseCvPreset } from '../cvPreset';

// Static guide pages are generated by scripts/guides/build.mjs and served as
// plain files; these checks guard the SEO essentials the generator promises.
const ROOT = join(process.cwd(), 'public');
const manifest = JSON.parse(readFileSync(join(ROOT, 'guides/manifest.json'), 'utf8')) as {
  pages: Array<{ path: string; title: string; lastmod: string; format?: string | null }>;
};

function readPage(path: string): string {
  return readFileSync(join(ROOT, path, 'index.html'), 'utf8');
}

describe('guides manifest', () => {
  it('lists the index and at least one guide, each with a file on disk', () => {
    expect(manifest.pages[0].path).toBe('/guides/');
    expect(manifest.pages.length).toBeGreaterThan(1);
    for (const p of manifest.pages) {
      expect(p.path).toMatch(/^\/guides\/([a-z0-9-]+\/)?$/);
      expect(p.lastmod).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(existsSync(join(ROOT, p.path, 'index.html'))).toBe(true);
    }
  });
});

describe.each(manifest.pages.filter(p => p.path !== '/guides/'))('guide $path', ({ path, format }) => {
  const html = readPage(path);

  it('has a canonical URL, OG tags and exactly one h1', () => {
    expect(html).toContain(`<link rel="canonical" href="https://scholarfolio.org${path}">`);
    expect(html).toContain(`<meta property="og:url" content="https://scholarfolio.org${path}">`);
    expect(html.match(/<h1>/g)).toHaveLength(1);
  });

  it('ships valid FAQPage JSON-LD', () => {
    const blocks = [...html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)].map(m => JSON.parse(m[1]));
    const faq = blocks.find(b => b['@type'] === 'FAQPage');
    expect(faq?.mainEntity.length).toBeGreaterThanOrEqual(3);
  });

  it('shows a last-checked date and at least one official source', () => {
    expect(html).toContain('Last checked');
    expect(html).toMatch(/<ul class="sources"><li><a href="https:\/\//);
  });

  it('links the CTA into the app with a preset the app understands', () => {
    const href = html.match(/<a class="btn" href="([^"]+)"/)?.[1]?.replace(/&amp;/g, '&');
    expect(href).toBeDefined();
    const preset = parseCvPreset(new URL(href as string, 'https://scholarfolio.org').search);
    expect(preset).toEqual({ openTab: true, format: format ?? null });
  });
});
